### ISSUE TITLE
Cannot read config file: node_modules/extend/.eslintrc

### ISSUE THREAD

**Issue by davidbarratt** [justmoon/node-extend#40]
Can we rename `.eslintrc` to `.eslintrc.json` to prevent `.eslintrc` from being parsed as YAML?
```
Cannot read config file: node_modules/extend/.eslintrc
Error: duplicated mapping key at line 45, column 30:
    			"beforeLineComment": false,
                                 ^
YAMLException: Cannot read config file: node_modules/extend/.eslintrc
Error: duplicated mapping key at line 45, column 30:
    			"beforeLineComment": false,
                                 ^
    at generateError (node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readFlowCollection (node_modules/js-yaml/lib/js-yaml/loader.js:720:7)
    at composeNode (node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (node_modules/js-yaml/lib/js-yaml/loader.js:704:5)
    at composeNode (node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (node_modules/js-yaml/lib/js-yaml/loader.js:715:7)
    at composeNode (node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (node_modules/js-yaml/lib/js-yaml/loader.js:715:7)
```

**Comment by ljharb** [comment]
I believe this is a bug in eslint or js-yaml - the default is json, so i'm not sure why it would attempt to parse it as yaml.

**Comment by solsos** [comment]
how did you fix it?
I met the same issue~

**Comment by joshfttb** [comment]
Having the same problem.

**Comment by ljharb** [comment]
@joshfttb what version of eslint are you running?

**Comment by joshfttb** [comment]
Sorry, just saw this.

eslint@3.8.0

**Comment by ljharb** [comment]
@joshfttb if you could make a repro repo, it might be an eslint bug.
